matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: osx
      osx_image: xcode10.2
language: generic
sudo: required
dist: trusty
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
script:
  - swift test
